# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'/projectimg')),
                ('link', models.TextField(blank=True, default=b'')),
                ('name', models.CharField(blank=True, default=b'', max_length=100)),
            ],
        ),
    ]
