# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-01 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_image',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'/aiffin'),
        ),
    ]
